main/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'  # here for namespacing of urls.

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("registro/", views.registro, name="registro"),
    path("login/", views.login_request, name="login_request"),
    path("logout/", views.logout_request, name="logout_request"),
    path("embutidos", views.embutidos, name="embutidos"),
    path("vegetales", views.vegetales, name="vegetales"),
    path("lacteos", views.lacteos, name="lacteos"),
    path("abarrotes", views.abarrotes, name="abarrotes"),
    path("limpieza", views.limpieza, name="limpieza"),
    path("licores", views.licores, name="licores"),
    #url(r'^add-to-cart/(?P<slug>\d{8,11}[\-].*)/$', cart_update, name="single"),
    path("cart_add", views.cart_add, name="cart_add"),
    path("remove_cart_item", views.remove_cart_item, name="remove_cart_item"),
    path("increase_quantity_cart_item", views.increase_quantity_cart_item, name="increase_quantity_cart_item"),
    path("reduce_quantity_cart_item", views.reduce_quantity_cart_item, name="reduce_quantity_cart_item"),
    path("checkout", views.checkout, name="checkout"),
    path("save_store_location", views.save_store_location, name="save_store_location"),
    path("submit_checkout", views.submit_checkout, name="submit_checkout"),
    path("get_nearby_shops", views.get_nearby_shops, name="get_nearby_shops"),

    # Dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/productos", views.productos, name="productos"),
    path("dashboard/mibodega", views.mibodega, name="mibodega"),
    path("dashboard/pedidos", views.pedidos, name="pedidos"),
    path("dashboard/save_product_changes", views.save_product_changes, name="save_product_changes"),
    path("dashboard/see_sales_detail", views.see_sales_detail, name="see_sales_detail"),
    path("dashboard/remove_product", views.remove_product, name="remove_product"),

    # Landing page
    path("unete", views.unete, name="unete"),
]

mibodega/urls.py
from django.contrib import admin
from django.urls import path, include

#DG
from django.conf import settings
from django.conf.urls.static import static
#

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Cliente, Cart

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ( # alll field names
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )
        
    email = forms.EmailField(required = True, max_length=254)
    first_name = forms.CharField(required = True, max_length=254)
    last_name = forms.CharField(required = True, max_length=254)

    def save(self, commit=True): #commit saves data to database
        user = super(RegistrationForm, self).save(commit=False) # when finish edition, it will store the data
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save() # saves the data

        return user

class ClientForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = (
            'cl_phone',
        )

    cl_phone = forms.CharField(required=True,max_length=9)

    def save(self, commit): #commit saves data to database
        client = super(ClientForm, self).save(commit=False) # when finish edition, it will store the data
        client.cl_phone = self.cleaned_data['cl_phone']

        if commit:
            client.save() # saves the data
        return client

class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = (
        )

    #cl_phone = forms.CharField(required=True,max_length=9)

    def save(self, commit): #commit saves data to database
        cart = super(CartForm, self).save(commit=False) # when finish edition, it will store the data
        #client.cl_phone = self.cleaned_data['cl_phone']

        if commit:
            cart.save() # saves the data
        return cart

main/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404 # to redirect the user
from .models import ProductosEnBodega, Cart, CartItem, Cliente, Bodega, Orders, BodegaOrders, OrderItem, BodegaDashboard, ProductosAprobados
from django.urls import reverse

from .forms import RegistrationForm, ClientForm
from django.contrib.auth import login as auth_login, logout as auth_logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages # to send unique messages to the users

from itertools import chain
from random import shuffle

from django.conf import settings

from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, HttpResponse

from django.core.mail import EmailMultiAlternatives #EmailMessage
from django.template.loader import render_to_string

from django.contrib.gis.geos import Point
from django.contrib.gis.db.models.functions import Distance
from ipregistry import IpregistryClient, NoCache

from django.db.models import Q

from datetime import date, datetime, timedelta
from dateutil.relativedelta import relativedelta

import base64
import requests
from decimal import *
import re # regex

import json
from django.http import JsonResponse

# Global variable Loads STATIC_URL
STATIC_URL = settings.STATIC_URL

def save_store_location(request):
    if request.method== "POST" and request.is_ajax():
        # Stores variables in session
        bodega_name = request.POST['bodega_name']
        request.session['bodega_name'] = bodega_name
        id_bodega = request.POST['id_bodega']
        request.session['id_bodega'] = id_bodega
        if request.user.is_authenticated:
#            print("Cliente identificado")
            cliente = Cliente.objects.all().filter(cl_user=request.user).first()
            cliente.cl_bodega_ID = id_bodega
            cliente.save()
        else:
            pass
#            print("Usuario no identificado")
    else:
        message = "Not Ajax"
    return HttpResponse("")

def locate_user():
    client = IpregistryClient("2cc3d6z6ct2weq", cache=NoCache())
    ipInfo = client.lookup()
    user_longitude = ipInfo.location['longitude']
    user_latitude = ipInfo.location['latitude']
    return user_longitude, user_latitude

def homepage(request):
    # FUTURE IMPROVEMENT. IF ipregistry SERVER FAILS, OUR SITE WILL CRASH
    # Locate user and shops nearby.
    try:
        if request.session['user_longitude'] is not None and request.session['user_latitude'] is not None:
#            print("Approx user location is known")
            user_longitude = request.session['user_longitude']
            user_latitude = request.session['user_latitude']
        else:
#            print("Approx user location is NOT known")
            user_longitude, user_latitude = locate_user()
    except:
#        print("Location does not exist in the session")
        user_longitude, user_latitude = locate_user()
        request.session['user_longitude'] = user_longitude
        request.session['user_latitude'] = user_latitude
    user_location = Point(user_longitude,user_latitude,srid=4326)
    shops = Bodega.objects.annotate(distance=Distance("bd_geolocation",user_location)).order_by("distance")[0:10]
    
    # Looks for products in the selected bodega
    productos_en_bodegas = ProductosEnBodega.objects.all()
    try:
        if request.session['id_bodega'] == "Cercanas":
 #           print("id_bodega is Empty")
            result_list = productos_en_bodegas.filter(peb_discount_rate__lt=0,peb_discount_status=True,peb_status=True)[:20]
        elif request.session['id_bodega'] != "Cercanas":
#            print("There is an id_bodega in session")
            result_list = productos_en_bodegas.filter(peb_discount_rate__lt=0,peb_discount_status=True,peb_status=True,peb_bodega__bd_ID=request.session['id_bodega'])[:20]
        else:
            pass
#            print("id_bodega is None")
    except:
#        print("id_bodega does not exist in the session")
        request.session['id_bodega'] = "Cercanas"
        request.session['bodega_name'] = "Cercanas"
        result_list = productos_en_bodegas.filter(peb_discount_rate__lt=0)[:20]
#        print(str(":")+str(request.session['id_bodega'])+str(":"))

    # Bodega name to display
    if request.session['bodega_name'] == "Cercanas":
        id_bodega_text = "Seleccione su bodega"
    elif request.session['bodega_name'] != "Cercanas":
        id_bodega_text = request.session['bodega_name']
    else:
        pass
#        print("What is this?")
    
    # Random shuffle the discount products
    temp = list(result_list)
    shuffle(temp)
    result_list = temp

    # Load or create cart
    cart_obj, new_obj = session_cart_load_or_create(request)
    # Load item list
    cart_list = CartItem.objects.all().filter(ci_cart_ID=cart_obj.crt_ID).all()

    return render(request=request, # to reference request
                  template_name="main/index.html", # where to find the specifix template
                  context={'result_list': result_list,
                           'cart_obj': cart_obj,
                           'cart_list': cart_list, 
                           'user_location': user_location,
                           'shops': shops,
                           'id_bodega_text': id_bodega_text})

def embutidos(request):
    # Locate user and shops nearby.
    try:
        if request.session['user_longitude'] is not None and request.session['user_latitude'] is not None:
            user_longitude = request.session['user_longitude']
            user_latitude = request.session['user_latitude']
        else:
            user_longitude, user_latitude = locate_user()
    except:
        user_longitude, user_latitude = locate_user()
        request.session['user_longitude'] = user_longitude
        request.session['user_latitude'] = user_latitude
    user_location = Point(user_longitude,user_latitude,srid=4326)
    shops = Bodega.objects.annotate(distance=Distance("bd_geolocation",user_location)).order_by("distance")[0:10]
        
    # Looks for products in the selected bodega
    productos_en_bodegas = ProductosEnBodega.objects.all().filter(peb_product__pa_category="embutidos",peb_status=True).all()
    try:
        if request.session['id_bodega'] == "Cercanas":
            result_list = productos_en_bodegas.all()
        elif request.session['id_bodega'] != "Cercanas":
            result_list = productos_en_bodegas.filter(peb_bodega__bd_ID=request.session['id_bodega']).all()
        else:
            pass
    except:
        request.session['id_bodega'] = "Cercanas"
        request.session['bodega_name'] = "Cercanas"
        result_list = productos_en_bodegas.filter(peb_discount_rate__lt=0)[:20]

    # Bodega name to display
    if request.session['bodega_name'] == "Cercanas":
        id_bodega_text = "Seleccione su bodega"
    elif request.session['bodega_name'] != "Cercanas":
        id_bodega_text = request.session['bodega_name']
    else:
        pass
#        print("What is this?")

    # Paginator
    page = request.GET.get('page', 1)
    paginator = Paginator(result_list, 12) # displayed products per page
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)
    result_count = paginator.count
    # Lookup for all the brands
    brands = []
    for product in result_list:
        # Check if brand already in the list
        if product.peb_product.pa_brand in brands:
            pass
        else:
            brands.append(product.peb_product.pa_brand)
    
    # Load or create cart
    cart_obj, new_obj = session_cart_load_or_create(request)
    # Load item list
    cart_list = CartItem.objects.all().filter(ci_cart_ID=cart_obj.crt_ID).all()

    return render(request=request, # to reference request
                  template_name="main/embutidos.html", # where to find the specifix template
                  context={'result_list': result_list,
                  'cart_obj': cart_obj,
                  'cart_list': cart_list,
                  'brands': brands,
                  'results': results,
                  'result_count': result_count,
                  'user_location': user_location,
                  'shops': shops,
                  'id_bodega_text': id_bodega_text,
                  'STATIC_URL': STATIC_URL})

def lacteos(request):
   # Locate user and shops nearby.
    try:
        if request.session['user_longitude'] is not None and request.session['user_latitude'] is not None:
            user_longitude = request.session['user_longitude']
            user_latitude = request.session['user_latitude']
        else:
            user_longitude, user_latitude = locate_user()
    except:
        user_longitude, user_latitude = locate_user()
        request.session['user_longitude'] = user_longitude
        request.session['user_latitude'] = user_latitude
    user_location = Point(user_longitude,user_latitude,srid=4326)
    shops = Bodega.objects.annotate(distance=Distance("bd_geolocation",user_location)).order_by("distance")[0:10]
        
    # Looks for products in the selected bodega
    productos_en_bodegas = ProductosEnBodega.objects.all().filter(peb_product__pa_category="lacteos",peb_status=True).all()
    try:
        if request.session['id_bodega'] == "Cercanas":
            result_list = productos_en_bodegas.all()
        elif request.session['id_bodega'] != "Cercanas":
            result_list = productos_en_bodegas.filter(peb_bodega__bd_ID=request.session['id_bodega']).all()
        else:
            pass
    except:
        request.session['id_bodega'] = "Cercanas"
        request.session['bodega_name'] = "Cercanas"
        result_list = productos_en_bodegas.filter(peb_discount_rate__lt=0)[:20]

    # Bodega name to display
    if request.session['bodega_name'] == "Cercanas":

main/templates/main/d-header.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="description" content="Alimentos.pe - ¡La bodega de tu barrio!">
    <meta name="keywords" content="Alimentos.pe, Tienda, Alimentos, Tienda online, bodega online, simple, online, comprar, shopping, descuentos, descuento, Alimentos, Comida, delivery, barato, económico, fresco">
	<meta name="viewport" content = "minimum-scale=1.0, width=device-width, initial-scale=1.0, user-scalable=no" >
	<meta name="format-detection" content="telephone=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Alimentos.pe</title>
	
	<!-- Css Styles -->
	<link rel="stylesheet" href="{% static 'main/css/dstyle.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'main/css/Chart.css' %}" type="text/css"> <!-- NEEDED FOR DRAWING CHARTS -->
	<link rel="stylesheet" href="{% static 'main/css/materialdesignicons.min.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'main/css/font-awesome.min.css' %}" type="text/css">
	<!--<link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}" type="text/css">-->
	<link rel="stylesheet" href="{% static 'main/css/slicknav.min.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'main/css/style.css' %}" type="text/css">
	<!-- Leaflet -->
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
	<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>
	<style>#mapid { height: 380px; }</style>
	<script src="https://cdn.jsdelivr.net/npm/leaflet@1.5.1/dist/leaflet.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.5.1/dist/leaflet.css"/>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>
    	
	<!-- ICONS (i.e. in the browser tab)-->
	<link rel="icon" href="{% static 'favicon.ico' %}">
	<!-- Icon/Tile for windows 8-->
	<meta name="application-name" content="Alimentos.pe">
</head>
<body>
    <!-- START ALERT MESSAGES SECTIONS-->
    {% include 'main/includes/messages.html' %}
    <!-- ENDS ALERT MESSAGES SECTIONS-->

    {% block content %}
    {% endblock %}    

	{% include 'main/includes/d-footer.html' %}
</body>

</html>

main/templates/main/embutidos - backup.html
{% extends 'main/header.html' %}
{% load static %}


{% block content %}
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Header Section Begin -->
<header class="header-section">
    <!-- MIDDLE BAR -->
    <div class="container">
        <div class="inner-header">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="logo">
                        <!-- <a href="./index.html"> -->
                            <img src="{% static 'main/img/logo.png' %}" alt="">
                        <!-- </a> -->
                    </div>
                </div>
                <div class="col-lg-7 col-md-7">
                    <div class="advanced-search">
                        <!--<button type="button" class="category-btn">All Categories</button>-->
                        <div class="input-group"> <!--Change width for adding all categories button-->
                            <input type="text" placeholder="Producto">
                            <button type="button"><i class="ti-search"></i></button>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 text-right col-md-3">
                    <ul class="nav-right">
                        <!-- SHOPPING CART -->
                        <li class="cart-icon">
                            <a href="#">
                                <i class="icon_bag_alt"></i>
                                <span>{{cart_list|length}}</span>
                            </a>
                            <div class="cart-hover">
                                <div class="select-items">
                                    <table>
                                        <tbody>
                                            {% load humanize %}
                                            {% for product in cart_list %}
                                            <tr>
                                                <td class="si-pic"><img src="{{ MEDIA_URL }}{{product.ci_product.peb_product.pa_category}}/{{product.ci_product.peb_product.pa_photo_small}}" alt=""></td>
                                                <td class="si-text">
                                                    <div class="product-selected">
                                                        <p>S/. 
                                                            {% if product.ci_product.peb_discount_status == True %}{{product.ci_product.peb_discount_price|floatformat:2|intcomma}}{% endif %}
                                                            {% if product.ci_product.peb_discount_status == False %}{{product.ci_product.peb_regular_price|floatformat:2|intcomma}}{% endif %}
                                                            x {{product.ci_quantity}}</p>
                                                        <h6>{{product.ci_product.peb_product.pa_product}}</h6>
                                                    </div>
                                                </td>
                                                <form method='POST' action='{% url "main:remove_cart" %}'> {% csrf_token %}
                                                    <td class="si-close">
                                                        <input type="hidden" name='item_pk' value='{{product.pk}}'>
                                                        <button type='submit'><i class="ti-close"></i></button>
                                                    </td>
                                                </form>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                                <div class="select-total">
                                    <span>total:</span>
                                    <h5>S/.{{cart_obj.crt_total_price}}</h5>
                                </div>
                                <div class="select-button">
                                    <a href="#" class="primary-btn view-card">VER CESTA</a>
                                    <a href="#" class="primary-btn checkout-btn">PAGAR</a>
                                </div>
                            </div>
                        </li>
                        <li class="cart-price">S/.{{cart_obj.crt_total_price}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- BOTTOM BAR-->
    <div class="nav-item">
        <div class="container">
            <nav class="nav-menu mobile-menu">
                <ul>
                    <li><a href="/">Ofertas</a></li>
                    <li class="active"><a href="/embutidos">Embutidos</a></li>
                    <li><a href="/vegetales">Vegetales</a>
                    <li><a href="/lacteos">Lácteos</a></li>
                    <li><a href="/abarrotes">Abarrotes</a></li>
                    <li><a href="/limpieza">Limpieza</a></li>
                    <li><a href="/licores">Licores</a>
                    </li>
                </ul>
            </nav>
            <!-- Mobile version-->
           <div id="mobile-menu-wrap"></div>
        </div>
    </div>
</header>
<!-- Header End -->

<!-- Product Shop Section Begin -->
<section class="product-shop spad">
    <div class="container">
        <div class="row">
            <!-- Brand filter section begin -->
            <div class="col-lg-3 col-md-6 col-sm-8 order-2 order-lg-1 produts-sidebar-filter">
                <div class="filter-widget">
                    <h4 class="fw-title">Marca</h4>
                    <div class="fw-brand-check">
                        {% for brand in brands %}
                        <div class="bc-item">
                            <label for="bc-calvin">
                                {{ brand }}
                                <input type="checkbox" id="bc-calvin">
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!-- Brand filter section end -->

            <!-- Search result area begin -->
            <div class="col-lg-9 order-1 order-lg-2">
                <div class="product-show-option">
                    <div class="row">
                        <div class="col-lg-7 col-md-7">
                            <div class="select-option">
                                <select class="sorting">
                                    <option value="">Default Sorting</option>
                                </select>
                                <select class="p-show">
                                    <option value="">Show:</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-5 col-md-5 text-right">
                            <p>Show 01- 09 Of 36 Product</p>
                        </div>
                    </div>
                </div>

                <div class="product-list">
                    <div class="row">
                        <!-- First item-->
                        {% load humanize %}
                        {% for product in result_list %}
                        <div class="col-lg-3 col-sm-4">
                            <div class="product-item">
                                <div class="pi-pic">
                                    <img src="{{ MEDIA_URL }}{{product.peb_product.pa_category}}/{{product.peb_product.pa_photo_small}}" alt="">
                                    {% if product.peb_discount_status == True %}
                                        <div class="sale pp-sale">{{ product.peb_discount_rate|floatformat:0|intcomma }} %</div>
                                    {% endif %}
                                    <ul>
                                        <form method='POST' action='{% url "main:cart_add" %}'> {% csrf_token %}
                                            <input type="hidden" name='product_id' value='{{product.pk}}'>
                                            <li class="quick-view"><input type='submit' value='Añadir a la cesta'></li>
                                        </form>        
                                    </ul>
                                </div>
                                <div class="pi-text">
                                    <div class="catagory-name">Towel</div>
                                    <a href="#">
                                        <h5>{{product.peb_product.pa_product}}</h5>
                                    </a>
                                    {% if product.peb_discount_status == True %}
                                    <div class="product-price">
                                        S/.{{product.peb_discount_price|floatformat:2|intcomma}}
                                        <span>S/.{{product.peb_regular_price|floatformat:2|intcomma}}</span>
                                    </div>
                                    {% else %}
                                    <div class="product-price">
                                        S/.{{product.peb_regular_price|floatformat:2|intcomma}}
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="loading-more">
                    <!--<i class="icon_loading"></i>
                    <a href="#">
                        Loading More
                    </a>-->
                </div>
            </div>
            <!-- Search result area end -->
        </div>
    </div>
</section>
<!-- Product Shop Section End -->

<!-- BENEFICIOS -->
<section class="latest-blog spad">
    <div class="container">
        <div class="benefit-items">
            <div class="row">
                <div class="col-lg-4" align="center">
                    <div class="single-benefit">
                        <div class="sb-icon">
                            <img src="{% static 'main/img/icon-1.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Envío económico</h6>
                            <p>Es la bodega de la cuadra.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4" align="center">
                    <div class="single-benefit">
                        <div class="sb-icon">
                            <img src="{% static 'main/img/icon-2.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Rápido envío</h6>
                            <p>El bodeguero es tu vecino.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4" align="center">
                    <div class="single-benefit">
                        <div class="sb-icon">
                            <img src="{% static 'main/img/icon-3.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>100% pago seguro</h6>
                            <p>En efectivo a <b>contraentrega.</b><br>Próximamente con tarjeta via web.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Latest Blog Section End -->
<!-- Js Plugins -->
<script src="{% static 'main/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>
<script src="{% static 'main/js/jquery-ui.min.js' %}"></script>
<script src="{% static 'main/js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'main/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'main/js/jquery.zoom.min.js' %}"></script>
<script src="{% static 'main/js/jquery.dd.min.js' %}"></script>
<script src="{% static 'main/js/jquery.slicknav.js' %}"></script>
<script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'main/js/main.js' %}"></script>
<!-- Infinite scroll -->
<script src="{% static 'main/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'main/js/infinite.min.js' %}"></script>
{% endblock %}